# Generated by Django 5.2.12 on 2026-03-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(default=None, upload_to='images', null=True),
            preserve_default=False,
        ),
    ]
